######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 3 22:11:52 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . Widgets
INCLUDEPATH += . Widgets
LIBS += -lpng -ljpeg -lQtInterface -lqwt -limagein 

# Input
HEADERS += Widgets/FilterEdition.h
SOURCES += main.cpp Widgets/FilterEdition.cpp
