######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 1 17:01:59 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . Widgets
INCLUDEPATH += . Widgets

# Input
HEADERS += Widgets/FilterEdition.h
SOURCES += main.cpp Widgets/FilterEdition.cpp
