######################################################################
# Automatically generated by qmake (2.01a) dim. avr. 1 17:31:37 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . Widgets
INCLUDEPATH += . Widgets

# Input
HEADERS += Widgets/FilterEdition.h
SOURCES += main.cpp Widgets/FilterEdition.cpp
