######################################################################
# Automatically generated by qmake (2.01a) jeu. mars 1 21:56:11 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ImageDelegate.h NavigationBar.h NavigationWidget.h
SOURCES += main.cpp
