######################################################################
# Automatically generated by qmake (2.01a) mar. févr. 28 20:30:15 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ImageDelegate.h NavigationBar.h
SOURCES += main.cpp
