######################################################################
# Automatically generated by qmake (2.01a) Fri May 25 18:19:38 2012
######################################################################

CONFIG += qtestlib
LIBS += -lpng -lz -ljpeg -lGenericInterface -limagein
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../../Applications/BasicApplication/BasicAlgorithmService.h
SOURCES += Tests.cpp \
           ../../Applications/BasicApplication/BasicAlgorithmService.cpp
