######################################################################
# Automatically generated by qmake (2.01a) Thu May 24 13:40:58 2012
######################################################################

CONFIG += qtestlib
LIBS += -limagein -lpng -ljpeg -lz -lGenericInterface
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Tests.h Tests.moc
SOURCES += Tests.cpp
